In [1]:
import pandas as pd

In [2]:
import bar_chart_race as bcr

In [3]:
df=pd.read_csv(r"C:\Users\Suri\Downloads\dataset.csv")

In [4]:
df.head()

,VIN (1-10),County,City,State,Postal Code,Model Year,Make,Model,Electric Vehicle Type,Clean Alternative Fuel Vehicle (CAFV) Eligibility,Electric Range,Base MSRP,Legislative District,DOL Vehicle ID,Vehicle Location,Electric Utility,2020 Census Tract
0,JTMEB3FV6N,Monroe,Key West,FL,33040,2022,TOYOTA,RAV4 PRIME,Plug-in Hybrid Electric Vehicle (PHEV),Clean Alternative Fuel Vehicle Eligible,42,0,NaN,198968248,POINT (-81.80023 24.5545),NaN,12087972100
1,1G1RD6E45D,Clark,Laughlin,NV,89029,2013,CHEVROLET,VOLT,Plug-in Hybrid Electric Vehicle (PHEV),Clean Alternative Fuel Vehicle Eligible,38,0,NaN,5204412,POINT (-114.57245 35.16815),NaN,32003005702
2,JN1AZ0CP8B,Yakima,Yakima,WA,98901,2011,NISSAN,LEAF,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,73,0,15.0,218972519,POINT (-120.50721 46.60448),PACIFICORP,53077001602
3,1G1FW6S08H,Skagit,Concrete,WA,98237,2017,CHEVROLET,BOLT EV,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,238,0,39.0,186750406,POINT (-121.7515 48.53892),PUGET SOUND ENERGY INC,53057951101
4,3FA6P0SU1K,Snohomish,Everett,WA,98201,2019,FORD,FUSION,Plug-in Hybrid Electric Vehicle (PHEV),Not eligible due to low battery range,26,0,38.0,2006714,POINT (-122.20596 47.97659),PUGET SOUND ENERGY INC,53061041500

In [73]:
pd.DataFrame(pd.crosstab(df["Model Year"],df["Make"])).to_csv("bar_chart_race.csv")

In [5]:
final=pd.read_csv(r"C:\Users\Suri\bar_chart_race.csv")
final.set_index("Model Year",inplace=True)

final.head(20)

,AUDI,AZURE DYNAMICS,BENTLEY,BMW,CADILLAC,CHEVROLET,CHRYSLER,FIAT,FISKER,FORD,...,POLESTAR,PORSCHE,RIVIAN,SMART,SUBARU,TESLA,TH!NK,TOYOTA,VOLKSWAGEN,VOLVO
Model Year,,,,,,,,,,,,,,,,,,,,,
1997,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1998,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1999,0,0,0,0,0,0,0,0,0,3,...,0,0,0,0,0,0,0,0,0,0
2000,0,0,0,0,0,0,0,0,0,10,...,0,0,0,0,0,0,0,0,0,0
2002,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,2,0,0
2008,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,23,0,0,0,0
2010,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,24,0,0,0,0
2011,0,4,0,0,0,71,0,0,0,0,...,0,0,0,0,0,7,3,0,0,0
2012,0,3,0,0,0,496,0,0,20,15,...,0,0,0,0,0,134,0,385,0,0
2013,0,0,0,0,0,818,0,106,0,662,...,0,0,0,29,0,814,0,296,0,0
2014,0,0,0,457,58,724,0,97,0,628,...,0,8,0,71,0,683,0,215,0,0
2015,0,0,0,403,0,467,0,242,0,556,...,0,33,0,52,0,1089,0,89,124,0
2016,214,0,0,383,18,309,0,148,0,778,...,0,78,0,31,0,1639,0,0,319,112
2017,187,0,0,692,15,2744,94,167,0,659,...,0,71,0,34,0,1679,0,899,52,115
2018,174,0,0,710,17,1126,554,53,0,170,...,0,78,0,47,0,7919,0,659,39,226
2019,392,0,0,279,0,966,119,9,0,136,...,0,62,0,9,58,4583,0,190,495,190
2020,224,0,1,143,0,1014,286,0,0,65,...,0,143,0,0,0,7018,0,311,0,162
2021,544,0,1,635,0,377,504,0,0,882,...,98,145,0,0,0,11028,0,935,988,580
2022,585,0,1,905,0,892,237,0,0,1250,...,372,200,885,0,0,14548,0,424,428,882
2023,12,0,0,73,0,177,0,0,0,4,...,88,0,0,0,1,890,0,0,69,21

In [7]:
import bar_chart_race as bcr
bcr.bar_chart_race(
    # must be a DataFrame where each row represents a single period of time.
    df=final,


    # name of the output video file
    filename="final.mp4",


    # specify location of image folder
    #img_label_folder="bar_image_labels",


    # change the Figure properties
    
)

C:\Users\Suri\anaconda3\lib\site-packages\bar_chart_race\_make_chart.py:286: UserWarning: FixedFormatter should only be used together with FixedLocator
  ax.set_yticklabels(self.df_values.columns)
C:\Users\Suri\anaconda3\lib\site-packages\bar_chart_race\_make_chart.py:287: UserWarning: FixedFormatter should only be used together with FixedLocator
  ax.set_xticklabels([max_val] * len(ax.get_xticks()))

In [41]:
!pip install bar_chart_race

Requirement already satisfied: bar_chart_race in c:\users\suri\anaconda3\lib\site-packages (0.1.0)
Requirement already satisfied: pandas>=0.24 in c:\users\suri\anaconda3\lib\site-packages (from bar_chart_race) (1.4.4)
Requirement already satisfied: matplotlib>=3.1 in c:\users\suri\anaconda3\lib\site-packages (from bar_chart_race) (3.5.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\suri\anaconda3\lib\site-packages (from matplotlib>=3.1->bar_chart_race) (2.8.2)
Requirement already satisfied: packaging>=20.0 in c:\users\suri\anaconda3\lib\site-packages (from matplotlib>=3.1->bar_chart_race) (21.3)
Requirement already satisfied: numpy>=1.17 in c:\users\suri\anaconda3\lib\site-packages (from matplotlib>=3.1->bar_chart_race) (1.21.5)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\suri\anaconda3\lib\site-packages (from matplotlib>=3.1->bar_chart_race) (4.25.0)
Requirement already satisfied: cycler>=0.10 in c:\users\suri\anaconda3\lib\site-packages (from matplotlib>=3.1->bar_chart_race) (0.11.0)
Requirement already satisfied: pillow>=6.2.0 in c:\users\suri\anaconda3\lib\site-packages (from matplotlib>=3.1->bar_chart_race) (9.2.0)
Requirement already satisfied: pyparsing>=2.2.1 in c:\users\suri\anaconda3\lib\site-packages (from matplotlib>=3.1->bar_chart_race) (3.0.9)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\suri\anaconda3\lib\site-packages (from matplotlib>=3.1->bar_chart_race) (1.4.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\suri\anaconda3\lib\site-packages (from pandas>=0.24->bar_chart_race) (2022.1)
Requirement already satisfied: six>=1.5 in c:\users\suri\anaconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib>=3.1->bar_chart_race) (1.16.0)

In [23]:
pwd

'C:\\Users\\Suri'

Collecting git+https://github.com/programiz/bar_chart_race.git@master
  Cloning https://github.com/programiz/bar_chart_race.git (to revision master) to c:\users\suri\appdata\local\temp\pip-req-build-9b_aprgb
Note: you may need to restart the kernel to use updated packages.

  ERROR: Error [WinError 2] The system cannot find the file specified while executing command git version
ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?

In [ ]:
conda install -c conda-forge ffmpeg